//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calorie.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calorie.Core.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure and reliable password generation.
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Password.
        /// </summary>
        public static string GeneratedPassword {
            get {
                return ResourceManager.GetString("GeneratedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password.
        /// </summary>
        public static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/About.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyn Calorie lets you create strong, unique passwords that you can always regenerate when you need them.
        ///By entering a master password and providing it with a seed (a word used when generating the password), you can retrieve the same generated password every time.
        ///You don&apos;t need to remember hundreds of passwords or rely on cloud services - just remember one master password and use simple seeds for each account.
        ///Neither the master password, the seed, nor the generated password is stored, so mali [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include special characters (!@#$%&amp;*-_+=).
        /// </summary>
        public static string IncludeSpecialChars {
            get {
                return ResourceManager.GetString("IncludeSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be between {0} and {1}.
        /// </summary>
        public static string LengthValidationError {
            get {
                return ResourceManager.GetString("LengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light .
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password cannot be empty.
        /// </summary>
        public static string MasterPasswordEmpty {
            get {
                return ResourceManager.GetString("MasterPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your master password.
        /// </summary>
        public static string MasterPasswordPlaceholder {
            get {
                return ResourceManager.GetString("MasterPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password is required.
        /// </summary>
        public static string MasterPasswordRequired {
            get {
                return ResourceManager.GetString("MasterPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length (8-256).
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a seed.
        /// </summary>
        public static string SeedPlaceholder {
            get {
                return ResourceManager.GetString("SeedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed is required.
        /// </summary>
        public static string SeedRequired {
            get {
                return ResourceManager.GetString("SeedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings are coming soon..
        /// </summary>
        public static string SettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The daily log is coming soon..
        /// </summary>
        public static string DailyLogComingSoon {
            get {
                return ResourceManager.GetString("DailyLogComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logging is coming soon..
        /// </summary>
        public static string NewLogEntryComingSoon {
            get {
                return ResourceManager.GetString("NewLogEntryComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string MealTypeBreakfast {
            get {
                return ResourceManager.GetString("MealTypeBreakfast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string MealTypeLunch {
            get {
                return ResourceManager.GetString("MealTypeLunch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string MealTypeDinner {
            get {
                return ResourceManager.GetString("MealTypeDinner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        public static string MealTypeSnack {
            get {
                return ResourceManager.GetString("MealTypeSnack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brunch.
        /// </summary>
        public static string MealTypeBrunch {
            get {
                return ResourceManager.GetString("MealTypeBrunch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supper.
        /// </summary>
        public static string MealTypeSupper {
            get {
                return ResourceManager.GetString("MealTypeSupper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treats.
        /// </summary>
        public static string MealTypeTreat {
            get {
                return ResourceManager.GetString("MealTypeTreat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logging to {0}.
        /// </summary>
        public static string LoggingToFormat {
            get {
                return ResourceManager.GetString("LoggingToFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log some meals and your week will build up here..
        /// </summary>
        public static string StatsEmptyHint {
            get {
                return ResourceManager.GetString("StatsEmptyHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing logged yet.
        /// </summary>
        public static string EmptyDayTitle {
            get {
                return ResourceManager.GetString("EmptyDayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap the + button to log the day's first meal..
        /// </summary>
        public static string EmptyDayHint {
            get {
                return ResourceManager.GetString("EmptyDayHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddFood {
            get {
                return ResourceManager.GetString("AddFood", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string ProteinShort {
            get {
                return ResourceManager.GetString("ProteinShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string CarbsShort {
            get {
                return ResourceManager.GetString("CarbsShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string FatShort {
            get {
                return ResourceManager.GetString("FatShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log food.
        /// </summary>
        public static string LogFoodTitle {
            get {
                return ResourceManager.GetString("LogFoodTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string TabMeals {
            get {
                return ResourceManager.GetString("TabMeals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string TabIngredients {
            get {
                return ResourceManager.GetString("TabIngredients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string TabScan {
            get {
                return ResourceManager.GetString("TabScan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning requires sign-in and is coming later..
        /// </summary>
        public static string ScanComingSoon {
            get {
                return ResourceManager.GetString("ScanComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount (grams).
        /// </summary>
        public static string AmountGramsLabel {
            get {
                return ResourceManager.GetString("AmountGramsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added to log.
        /// </summary>
        public static string ItemLogged {
            get {
                return ResourceManager.GetString("ItemLogged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string LibraryTitle {
            get {
                return ResourceManager.GetString("LibraryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New meal.
        /// </summary>
        public static string NewMeal {
            get {
                return ResourceManager.GetString("NewMeal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New ingredient.
        /// </summary>
        public static string NewIngredient {
            get {
                return ResourceManager.GetString("NewIngredient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brand (optional).
        /// </summary>
        public static string BrandLabel {
            get {
                return ResourceManager.GetString("BrandLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nutrition per 100 g.
        /// </summary>
        public static string NutritionPer100gHeader {
            get {
                return ResourceManager.GetString("NutritionPer100gHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calories (kcal).
        /// </summary>
        public static string CaloriesLabel {
            get {
                return ResourceManager.GetString("CaloriesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protein (g).
        /// </summary>
        public static string ProteinLabel {
            get {
                return ResourceManager.GetString("ProteinLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates (g).
        /// </summary>
        public static string CarbsLabel {
            get {
                return ResourceManager.GetString("CarbsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fat (g).
        /// </summary>
        public static string FatLabel {
            get {
                return ResourceManager.GetString("FatLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Piece support (optional).
        /// </summary>
        public static string UnitSectionHeader {
            get {
                return ResourceManager.GetString("UnitSectionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unit name (e.g. pcs, slice).
        /// </summary>
        public static string UnitNameLabel {
            get {
                return ResourceManager.GetString("UnitNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weight per unit (g).
        /// </summary>
        public static string UnitWeightLabel {
            get {
                return ResourceManager.GetString("UnitWeightLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add ingredient.
        /// </summary>
        public static string AddIngredientToMeal {
            get {
                return ResourceManager.GetString("AddIngredientToMeal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string GoalsTitle {
            get {
                return ResourceManager.GetString("GoalsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Daily goal (kcal).
        /// </summary>
        public static string DailyGoalLabel {
            get {
                return ResourceManager.GetString("DailyGoalLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upper limit.
        /// </summary>
        public static string ModeLimit {
            get {
                return ResourceManager.GetString("ModeLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target to reach.
        /// </summary>
        public static string ModeTarget {
            get {
                return ResourceManager.GetString("ModeTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Macro goals (optional).
        /// </summary>
        public static string MacroGoalsHeader {
            get {
                return ResourceManager.GetString("MacroGoalsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Budget per meal (optional, kcal).
        /// </summary>
        public static string MealBudgetsHeader {
            get {
                return ResourceManager.GetString("MealBudgetsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Statistics arrive once local storage is in place..
        /// </summary>
        public static string StatsComingSoon {
            get {
                return ResourceManager.GetString("StatsComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avg/day.
        /// </summary>
        public static string WeekAverage {
            get {
                return ResourceManager.GetString("WeekAverage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On track.
        /// </summary>
        public static string DaysOnTrack {
            get {
                return ResourceManager.GetString("DaysOnTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logged.
        /// </summary>
        public static string LoggedDays {
            get {
                return ResourceManager.GetString("LoggedDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Per meal type.
        /// </summary>
        public static string MealDistribution {
            get {
                return ResourceManager.GetString("MealDistribution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing logged this week..
        /// </summary>
        public static string NoDataThisWeek {
            get {
                return ResourceManager.GetString("NoDataThisWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches in your library..
        /// </summary>
        public static string NoLibraryMatches {
            get {
                return ResourceManager.GetString("NoLibraryMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap "{0}" to create it..
        /// </summary>
        public static string CreateItemHint {
            get {
                return ResourceManager.GetString("CreateItemHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ingredient saved.
        /// </summary>
        public static string IngredientSaved {
            get {
                return ResourceManager.GetString("IngredientSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meal saved.
        /// </summary>
        public static string MealSaved {
            get {
                return ResourceManager.GetString("MealSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customize meal.
        /// </summary>
        public static string CustomizeMeal {
            get {
                return ResourceManager.GetString("CustomizeMeal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use in log.
        /// </summary>
        public static string UseInLog {
            get {
                return ResourceManager.GetString("UseInLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update template too.
        /// </summary>
        public static string UpdateTemplateToo {
            get {
                return ResourceManager.GetString("UpdateTemplateToo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to customized.
        /// </summary>
        public static string CustomizedLabel {
            get {
                return ResourceManager.GetString("CustomizedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manual nutrition.
        /// </summary>
        public static string ManualNutrition {
            get {
                return ResourceManager.GetString("ManualNutrition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package weight (g).
        /// </summary>
        public static string PackageWeightLabel {
            get {
                return ResourceManager.GetString("PackageWeightLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Per 100 g.
        /// </summary>
        public static string Per100gLabel {
            get {
                return ResourceManager.GetString("Per100gLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Per package.
        /// </summary>
        public static string PerPackageLabel {
            get {
                return ResourceManager.GetString("PerPackageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to package.
        /// </summary>
        public static string PackageUnitName {
            get {
                return ResourceManager.GetString("PackageUnitName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entry deleted.
        /// </summary>
        public static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treat share of daily goal (%, optional).
        /// </summary>
        public static string TreatShareLabel {
            get {
                return ResourceManager.GetString("TreatShareLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to = {0} kcal.
        /// </summary>
        public static string TreatShareCalculated {
            get {
                return ResourceManager.GetString("TreatShareCalculated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} kcal treats left.
        /// </summary>
        public static string TreatRemainingFormat {
            get {
                return ResourceManager.GetString("TreatRemainingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} kcal treats over.
        /// </summary>
        public static string TreatOverFormat {
            get {
                return ResourceManager.GetString("TreatOverFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ingredient deleted.
        /// </summary>
        public static string IngredientDeleted {
            get {
                return ResourceManager.GetString("IngredientDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meal deleted.
        /// </summary>
        public static string MealDeleted {
            get {
                return ResourceManager.GetString("MealDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The ingredient is used in a meal and can't be deleted.
        /// </summary>
        public static string IngredientInUse {
            get {
                return ResourceManager.GetString("IngredientInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
    }
}
