// <auto-generated />
using System;
using Lyn.Backend.Apps.Calorie.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyn.Backend.Apps.Calorie.Persistence.Migrations
{
    [DbContext(typeof(CalorieDbContext))]
    partial class CalorieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.FoodProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("UnitName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnitWeightGrams")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ean")
                        .IsUnique();

                    b.ToTable("FoodProducts");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FoodProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnitWeightGrams")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LoggedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "LoggedDate");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.LogEntryIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountGrams")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LogEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.ToTable("LogEntryIngredients");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.MealBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCalories")
                        .HasColumnType("integer");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserGoalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGoalId", "MealType")
                        .IsUnique();

                    b.ToTable("MealBudgets");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.MealIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountGrams")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId", "IngredientId")
                        .IsUnique();

                    b.ToTable("MealIngredients");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CarbsGrams")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date");

                    b.Property<int?>("FatGrams")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("ProteinGrams")
                        .HasColumnType("integer");

                    b.Property<int?>("TreatPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EffectiveFromDate")
                        .IsUnique();

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.FoodProduct", b =>
                {
                    b.OwnsOne("Lyn.Backend.Apps.Calorie.Models.StoredImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("FoodProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ImageContentType");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageStorageKey");

                            b1.Property<string>("ThumbnailKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageThumbnailKey");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ImageUploadedAtUtc");

                            b1.HasKey("FoodProductId");

                            b1.ToTable("FoodProducts");

                            b1.WithOwner()
                                .HasForeignKey("FoodProductId");
                        });

                    b.OwnsOne("Lyn.Backend.Apps.Calorie.Models.NutritionPer100G", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("FoodProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("CaloriesPer100g");

                            b1.Property<decimal>("Carbs")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("CarbsPer100g");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("FatPer100g");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("ProteinPer100g");

                            b1.HasKey("FoodProductId");

                            b1.ToTable("FoodProducts");

                            b1.WithOwner()
                                .HasForeignKey("FoodProductId");
                        });

                    b.Navigation("Image");

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.Ingredient", b =>
                {
                    b.HasOne("Lyn.Backend.Apps.Calorie.Models.FoodProduct", "FoodProduct")
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Lyn.Backend.Apps.Calorie.Models.StoredImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ImageContentType");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageStorageKey");

                            b1.Property<string>("ThumbnailKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageThumbnailKey");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ImageUploadedAtUtc");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.OwnsOne("Lyn.Backend.Apps.Calorie.Models.NutritionPer100G", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("CaloriesPer100g");

                            b1.Property<decimal>("Carbs")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("CarbsPer100g");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("FatPer100g");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("ProteinPer100g");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("FoodProduct");

                    b.Navigation("Image");

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.LogEntry", b =>
                {
                    b.HasOne("Lyn.Backend.Apps.Calorie.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.LogEntryIngredient", b =>
                {
                    b.HasOne("Lyn.Backend.Apps.Calorie.Models.LogEntry", "LogEntry")
                        .WithMany("Ingredients")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lyn.Backend.Apps.Calorie.Models.NutritionPer100G", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("LogEntryIngredientId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("CaloriesPer100g");

                            b1.Property<decimal>("Carbs")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("CarbsPer100g");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("FatPer100g");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("ProteinPer100g");

                            b1.HasKey("LogEntryIngredientId");

                            b1.ToTable("LogEntryIngredients");

                            b1.WithOwner()
                                .HasForeignKey("LogEntryIngredientId");
                        });

                    b.Navigation("LogEntry");

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.Meal", b =>
                {
                    b.OwnsOne("Lyn.Backend.Apps.Calorie.Models.StoredImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ImageContentType");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageStorageKey");

                            b1.Property<string>("ThumbnailKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageThumbnailKey");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ImageUploadedAtUtc");

                            b1.HasKey("MealId");

                            b1.ToTable("Meals");

                            b1.WithOwner()
                                .HasForeignKey("MealId");
                        });

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.MealBudget", b =>
                {
                    b.HasOne("Lyn.Backend.Apps.Calorie.Models.UserGoal", "UserGoal")
                        .WithMany("MealBudgets")
                        .HasForeignKey("UserGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGoal");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.MealIngredient", b =>
                {
                    b.HasOne("Lyn.Backend.Apps.Calorie.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lyn.Backend.Apps.Calorie.Models.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.LogEntry", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Lyn.Backend.Apps.Calorie.Models.UserGoal", b =>
                {
                    b.Navigation("MealBudgets");
                });
#pragma warning restore 612, 618
        }
    }
}
